spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: kyh-spring-plus-bucket

logging:
  level:
    root: INFO