# PR & Push 검증 (빌드 + 테스트)
name: CI

on:
  push:
    branches:
      - "feat/**"
      - dev
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ci-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable-build.yml
    with:
      run-tests: true