# PR & Push 검증 (빌드 + 테스트)
name: CI

on:
  push:
    branches:
      - "feat/**"
      - dev
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "docs/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable-build.yml
    with:
      run-tests: true