# 공통 빌드 로직
name: Reusable Build

on:
  workflow_call:
    inputs:
      run-tests:
        description: 'Whether to run tests'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build (with tests)
        if: ${{ inputs['run-tests'] == true }}
        run: ./gradlew clean build --no-daemon

      - name: Build (skip tests)
        if: ${{ inputs['run-tests'] != true }}
        run: ./gradlew clean build --no-daemon -x test